export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT  = "UPDATE_PRODUCT"
export const Add_PRODUCTS = "Add_PRODUCTS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_SINGLE_PRODUCTS = "FETCH_SINGLE_PRODUCTS";
export const UPDATE_LOADER = "UPDATE_LOADER";

